version: '2'
services:
    reviewmania-app:
        image: reviewmania
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://reviewmania-mysql:3306/reviewmania?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    reviewmania-mysql:
        extends:
            file: mysql.yml
            service: reviewmania-mysql
